language: node_js
node_js: lts/*
install: npm install
# TODO: investigate why this causes issues
# cache:
#   directories:
#     - node_modules
jobs:
  include:
    - stage: test
      name: "Test"
      script: npm test
